modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20TNT%20Breaks%20Bedrock"
logoFile="icon.png"

[[mods]]
modId="tntbreaksbedrock"
version="3.4"
displayName="TNT Breaks Bedrock"
displayURL="https://serilum.com/mod/tnt-breaks-bedrock"
authors="Rick South"
description='''Allows TNT to break bedrock. Now you've finally got easy access to the nether roof.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.tntbreaksbedrock]]
    modId="collective"
    type="required"
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tntbreaksbedrock]]
    modId="minecraft"
    type="required"
    versionRange="[1.21]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "tntbreaksbedrock.mixins.json"